import { defineStore } from "pinia";
import { computed, ref } from "vue";

export interface Attraction {
	id: number;
	name: string;
	category: string;
	address: string;
	latitude: number;
	longitude: number;
	description: string;
	imageUrl: string;
	rating: number;
	reviewCount: number;
	sido: string;
	gugun: string;
	contentTypeId: number;
}

// V3 시드 기반 여행지 50건 (일부 인용)
const SEED_ATTRACTIONS: Attraction[] = [
	{
		id: 1,
		name: "경복궁",
		category: "문화재",
		address: "서울특별시 종로구 사직로 161",
		latitude: 37.5796,
		longitude: 126.977,
		description: "조선 왕조의 법궁으로 1395년에 창건된 궁궐입니다.",
		imageUrl: "https://picsum.photos/seed/gyeongbokgung/400/300",
		rating: 4.7,
		reviewCount: 12450,
		sido: "서울",
		gugun: "종로구",
		contentTypeId: 76,
	},
	{
		id: 2,
		name: "남산서울타워",
		category: "관광지",
		address: "서울특별시 용산구 남산공원길 105",
		latitude: 37.5512,
		longitude: 126.9882,
		description: "서울 전망을 한눈에 볼 수 있는 랜드마크 타워입니다.",
		imageUrl: "https://picsum.photos/seed/namsan/400/300",
		rating: 4.5,
		reviewCount: 9832,
		sido: "서울",
		gugun: "용산구",
		contentTypeId: 76,
	},
	{
		id: 3,
		name: "해운대 해수욕장",
		category: "해변",
		address: "부산광역시 해운대구 해운대해변로 264",
		latitude: 35.1587,
		longitude: 129.1604,
		description: "부산을 대표하는 해수욕장으로 국내 최대 규모입니다.",
		imageUrl: "https://picsum.photos/seed/haeundae/400/300",
		rating: 4.6,
		reviewCount: 18920,
		sido: "부산",
		gugun: "해운대구",
		contentTypeId: 39,
	},
	{
		id: 4,
		name: "제주 성산일출봉",
		category: "자연",
		address: "제주특별자치도 서귀포시 성산읍 일출로 284-12",
		latitude: 33.4581,
		longitude: 126.9425,
		description: "유네스코 세계자연유산으로 등재된 제주의 상징적인 오름입니다.",
		imageUrl: "https://picsum.photos/seed/seongsan/400/300",
		rating: 4.8,
		reviewCount: 21300,
		sido: "제주",
		gugun: "서귀포시",
		contentTypeId: 12,
	},
	{
		id: 5,
		name: "창덕궁",
		category: "문화재",
		address: "서울특별시 종로구 율곡로 99",
		latitude: 37.5792,
		longitude: 126.9908,
		description: "유네스코 세계문화유산으로 등재된 조선 시대 궁궐입니다.",
		imageUrl: "https://picsum.photos/seed/changdeok/400/300",
		rating: 4.6,
		reviewCount: 8760,
		sido: "서울",
		gugun: "종로구",
		contentTypeId: 76,
	},
	{
		id: 6,
		name: "광안리 해수욕장",
		category: "해변",
		address: "부산광역시 수영구 광안해변로 219",
		latitude: 35.1531,
		longitude: 129.1185,
		description: "광안대교가 보이는 아름다운 해변으로 야경이 유명합니다.",
		imageUrl: "https://picsum.photos/seed/gwangan/400/300",
		rating: 4.5,
		reviewCount: 14500,
		sido: "부산",
		gugun: "수영구",
		contentTypeId: 39,
	},
	{
		id: 7,
		name: "한라산 국립공원",
		category: "자연",
		address: "제주특별자치도 제주시 1100로 2070-61",
		latitude: 33.3617,
		longitude: 126.5292,
		description: "대한민국 최고봉 한라산이 있는 국립공원입니다.",
		imageUrl: "https://picsum.photos/seed/hallasan/400/300",
		rating: 4.9,
		reviewCount: 16800,
		sido: "제주",
		gugun: "제주시",
		contentTypeId: 12,
	},
	{
		id: 8,
		name: "인사동",
		category: "쇼핑/문화",
		address: "서울특별시 종로구 인사동길",
		latitude: 37.5739,
		longitude: 126.9854,
		description: "전통문화와 현대예술이 공존하는 서울의 대표 문화거리입니다.",
		imageUrl: "https://picsum.photos/seed/insadong/400/300",
		rating: 4.3,
		reviewCount: 7890,
		sido: "서울",
		gugun: "종로구",
		contentTypeId: 32,
	},
	{
		id: 9,
		name: "감천문화마을",
		category: "문화",
		address: "부산광역시 사하구 감내2로 203",
		latitude: 35.0977,
		longitude: 129.0108,
		description: "알록달록한 벽화로 유명한 부산의 문화마을입니다.",
		imageUrl: "https://picsum.photos/seed/gamcheon/400/300",
		rating: 4.4,
		reviewCount: 11200,
		sido: "부산",
		gugun: "사하구",
		contentTypeId: 14,
	},
	{
		id: 10,
		name: "경주 불국사",
		category: "문화재",
		address: "경상북도 경주시 불국로 385",
		latitude: 35.7903,
		longitude: 129.3317,
		description: "신라 시대 건립된 유네스코 세계문화유산 사찰입니다.",
		imageUrl: "https://picsum.photos/seed/bulguksa/400/300",
		rating: 4.7,
		reviewCount: 13400,
		sido: "경북",
		gugun: "경주시",
		contentTypeId: 76,
	},
	{
		id: 11,
		name: "설악산 국립공원",
		category: "자연",
		address: "강원도 속초시 설악산로 833",
		latitude: 38.119,
		longitude: 128.4656,
		description: "단풍으로 유명한 강원도 대표 국립공원입니다.",
		imageUrl: "https://picsum.photos/seed/seoraksan/400/300",
		rating: 4.8,
		reviewCount: 19200,
		sido: "강원",
		gugun: "속초시",
		contentTypeId: 12,
	},
	{
		id: 12,
		name: "덕수궁",
		category: "문화재",
		address: "서울특별시 중구 세종대로 99",
		latitude: 37.5654,
		longitude: 126.9753,
		description: "대한제국 시기 황궁으로 사용된 궁궐입니다.",
		imageUrl: "https://picsum.photos/seed/deoksugung/400/300",
		rating: 4.4,
		reviewCount: 6540,
		sido: "서울",
		gugun: "중구",
		contentTypeId: 76,
	},
	{
		id: 13,
		name: "제주 협재해수욕장",
		category: "해변",
		address: "제주특별자치도 제주시 한림읍 협재리 2497-1",
		latitude: 33.3939,
		longitude: 126.2398,
		description: "에메랄드빛 바다와 흰 모래가 아름다운 제주 해변입니다.",
		imageUrl: "https://picsum.photos/seed/hyeopjae/400/300",
		rating: 4.7,
		reviewCount: 10800,
		sido: "제주",
		gugun: "제주시",
		contentTypeId: 39,
	},
	{
		id: 14,
		name: "북촌한옥마을",
		category: "문화",
		address: "서울특별시 종로구 계동길 37",
		latitude: 37.5824,
		longitude: 126.9849,
		description: "조선 시대 양반들이 살았던 한옥이 밀집한 마을입니다.",
		imageUrl: "https://picsum.photos/seed/bukchon/400/300",
		rating: 4.3,
		reviewCount: 9100,
		sido: "서울",
		gugun: "종로구",
		contentTypeId: 14,
	},
	{
		id: 15,
		name: "전주 한옥마을",
		category: "문화",
		address: "전라북도 전주시 완산구 기린대로 99",
		latitude: 35.8153,
		longitude: 127.1532,
		description: "700여 채의 한옥이 보존된 국내 최대 규모의 한옥마을입니다.",
		imageUrl: "https://picsum.photos/seed/jeonju/400/300",
		rating: 4.6,
		reviewCount: 17600,
		sido: "전북",
		gugun: "전주시",
		contentTypeId: 14,
	},
	{
		id: 16,
		name: "순천만 국가정원",
		category: "자연",
		address: "전라남도 순천시 국가정원1호길 47",
		latitude: 34.9217,
		longitude: 127.504,
		description: "아름다운 갈대밭과 습지로 유명한 생태 정원입니다.",
		imageUrl: "https://picsum.photos/seed/suncheon/400/300",
		rating: 4.5,
		reviewCount: 8900,
		sido: "전남",
		gugun: "순천시",
		contentTypeId: 12,
	},
	{
		id: 17,
		name: "지리산 국립공원",
		category: "자연",
		address: "경남 산청군 시천면 지리산대로 2",
		latitude: 35.3372,
		longitude: 127.7322,
		description: "남한 최고의 명산으로 다양한 등산 코스를 자랑합니다.",
		imageUrl: "https://picsum.photos/seed/jirisan/400/300",
		rating: 4.7,
		reviewCount: 14100,
		sido: "경남",
		gugun: "산청군",
		contentTypeId: 12,
	},
	{
		id: 18,
		name: "제주 올레길 1코스",
		category: "트레킹",
		address: "제주특별자치도 서귀포시 성산읍",
		latitude: 33.4498,
		longitude: 126.9308,
		description: "제주의 자연을 만끽할 수 있는 올레길 1코스입니다.",
		imageUrl: "https://picsum.photos/seed/olle1/400/300",
		rating: 4.6,
		reviewCount: 9400,
		sido: "제주",
		gugun: "서귀포시",
		contentTypeId: 12,
	},
	{
		id: 19,
		name: "속초 아바이마을",
		category: "문화",
		address: "강원도 속초시 청호동 1-3",
		latitude: 38.2108,
		longitude: 128.5933,
		description: "실향민들이 정착한 마을로 순대와 오징어순대로 유명합니다.",
		imageUrl: "https://picsum.photos/seed/abai/400/300",
		rating: 4.2,
		reviewCount: 5600,
		sido: "강원",
		gugun: "속초시",
		contentTypeId: 14,
	},
	{
		id: 20,
		name: "안동 하회마을",
		category: "문화재",
		address: "경상북도 안동시 풍천면 하회리",
		latitude: 36.5396,
		longitude: 128.5193,
		description: "유네스코 세계문화유산으로 등재된 전통 민속마을입니다.",
		imageUrl: "https://picsum.photos/seed/hahoe/400/300",
		rating: 4.6,
		reviewCount: 11800,
		sido: "경북",
		gugun: "안동시",
		contentTypeId: 76,
	},
	{
		id: 21,
		name: "남이섬",
		category: "관광지",
		address: "강원도 춘천시 남산면 남이섬길 1",
		latitude: 37.7914,
		longitude: 127.5259,
		description: "드라마 겨울연가로 유명한 아름다운 섬입니다.",
		imageUrl: "https://picsum.photos/seed/namisum/400/300",
		rating: 4.5,
		reviewCount: 22100,
		sido: "강원",
		gugun: "춘천시",
		contentTypeId: 12,
	},
	{
		id: 22,
		name: "오죽헌",
		category: "문화재",
		address: "강원도 강릉시 율곡로 3139번길 24",
		latitude: 37.7516,
		longitude: 128.8748,
		description: "신사임당과 율곡 이이의 생가로 알려진 조선시대 건물입니다.",
		imageUrl: "https://picsum.photos/seed/ojukheon/400/300",
		rating: 4.3,
		reviewCount: 4800,
		sido: "강원",
		gugun: "강릉시",
		contentTypeId: 76,
	},
	{
		id: 23,
		name: "부산 자갈치시장",
		category: "시장",
		address: "부산광역시 중구 자갈치해안로 52",
		latitude: 35.0968,
		longitude: 129.0303,
		description:
			"신선한 해산물을 저렴하게 즐길 수 있는 부산 최대 어시장입니다.",
		imageUrl: "https://picsum.photos/seed/jagalchi/400/300",
		rating: 4.3,
		reviewCount: 8700,
		sido: "부산",
		gugun: "중구",
		contentTypeId: 38,
	},
	{
		id: 24,
		name: "통영 케이블카",
		category: "관광지",
		address: "경상남도 통영시 발개로 205",
		latitude: 34.8448,
		longitude: 128.4213,
		description: "한려수도의 절경을 내려다볼 수 있는 케이블카입니다.",
		imageUrl: "https://picsum.photos/seed/tongyeong/400/300",
		rating: 4.4,
		reviewCount: 6200,
		sido: "경남",
		gugun: "통영시",
		contentTypeId: 76,
	},
	{
		id: 25,
		name: "여수 돌산도",
		category: "자연",
		address: "전라남도 여수시 돌산읍",
		latitude: 34.7086,
		longitude: 127.7408,
		description: "밤바다와 낭만적인 야경으로 유명한 여수의 명소입니다.",
		imageUrl: "https://picsum.photos/seed/dolsan/400/300",
		rating: 4.5,
		reviewCount: 7800,
		sido: "전남",
		gugun: "여수시",
		contentTypeId: 12,
	},
	{
		id: 26,
		name: "수원 화성",
		category: "문화재",
		address: "경기도 수원시 팔달구 화서동 115",
		latitude: 37.2874,
		longitude: 127.0137,
		description: "유네스코 세계문화유산으로 등재된 조선 시대 성곽입니다.",
		imageUrl: "https://picsum.photos/seed/hwaseong/400/300",
		rating: 4.5,
		reviewCount: 9300,
		sido: "경기",
		gugun: "수원시",
		contentTypeId: 76,
	},
	{
		id: 27,
		name: "제주 천지연폭포",
		category: "자연",
		address: "제주특별자치도 서귀포시 천지동 667-7",
		latitude: 33.2481,
		longitude: 126.5515,
		description: "울창한 숲과 아름다운 폭포가 어우러진 제주의 명소입니다.",
		imageUrl: "https://picsum.photos/seed/cheonjiyeon/400/300",
		rating: 4.4,
		reviewCount: 8200,
		sido: "제주",
		gugun: "서귀포시",
		contentTypeId: 12,
	},
	{
		id: 28,
		name: "강릉 경포대",
		category: "자연",
		address: "강원도 강릉시 경포로 365",
		latitude: 37.7956,
		longitude: 128.9058,
		description: "관동팔경 중 하나로 아름다운 해변으로 유명합니다.",
		imageUrl: "https://picsum.photos/seed/gyeongpodae/400/300",
		rating: 4.4,
		reviewCount: 7600,
		sido: "강원",
		gugun: "강릉시",
		contentTypeId: 12,
	},
	{
		id: 29,
		name: "인천 차이나타운",
		category: "문화",
		address: "인천광역시 중구 차이나타운로 56번길",
		latitude: 37.4755,
		longitude: 126.6179,
		description: "국내 유일의 차이나타운으로 중화요리 거리로 유명합니다.",
		imageUrl: "https://picsum.photos/seed/chinatown/400/300",
		rating: 4.1,
		reviewCount: 5400,
		sido: "인천",
		gugun: "중구",
		contentTypeId: 14,
	},
	{
		id: 30,
		name: "경주 석굴암",
		category: "문화재",
		address: "경상북도 경주시 진현동 999",
		latitude: 35.8096,
		longitude: 129.3604,
		description: "신라 시대 건립된 석굴 불상으로 유네스코 세계문화유산입니다.",
		imageUrl: "https://picsum.photos/seed/seokguram/400/300",
		rating: 4.7,
		reviewCount: 10500,
		sido: "경북",
		gugun: "경주시",
		contentTypeId: 76,
	},
	{
		id: 31,
		name: "태안 꽃지해수욕장",
		category: "해변",
		address: "충청남도 태안군 안면읍 승언리",
		latitude: 36.5228,
		longitude: 126.374,
		description: "낙조가 아름다운 서해의 대표 해수욕장입니다.",
		imageUrl: "https://picsum.photos/seed/kochi/400/300",
		rating: 4.4,
		reviewCount: 6800,
		sido: "충남",
		gugun: "태안군",
		contentTypeId: 39,
	},
	{
		id: 32,
		name: "담양 메타세쿼이아 길",
		category: "자연",
		address: "전라남도 담양군 담양읍 메타세쿼이아로 12",
		latitude: 35.3383,
		longitude: 126.9876,
		description: "드라이브 코스로 인기 있는 가을 단풍 명소입니다.",
		imageUrl: "https://picsum.photos/seed/metasequoia/400/300",
		rating: 4.5,
		reviewCount: 9800,
		sido: "전남",
		gugun: "담양군",
		contentTypeId: 12,
	},
	{
		id: 33,
		name: "보성 녹차밭",
		category: "자연",
		address: "전라남도 보성군 보성읍 녹차로 775",
		latitude: 34.7772,
		longitude: 127.0815,
		description: "끝없이 펼쳐진 녹차밭이 아름다운 힐링 명소입니다.",
		imageUrl: "https://picsum.photos/seed/boseong/400/300",
		rating: 4.5,
		reviewCount: 8400,
		sido: "전남",
		gugun: "보성군",
		contentTypeId: 12,
	},
	{
		id: 34,
		name: "속리산 법주사",
		category: "문화재",
		address: "충청북도 보은군 속리산면 법주사로 405",
		latitude: 36.5417,
		longitude: 127.8175,
		description: "신라 시대 창건된 사찰로 국보와 보물이 다수 있습니다.",
		imageUrl: "https://picsum.photos/seed/beopjusa/400/300",
		rating: 4.4,
		reviewCount: 5700,
		sido: "충북",
		gugun: "보은군",
		contentTypeId: 76,
	},
	{
		id: 35,
		name: "울릉도 독도",
		category: "자연",
		address: "경상북도 울릉군 울릉읍 독도리",
		latitude: 37.2426,
		longitude: 131.8659,
		description:
			"대한민국 가장 동쪽에 위치한 섬으로 천혜의 자연환경을 자랑합니다.",
		imageUrl: "https://picsum.photos/seed/dokdo/400/300",
		rating: 4.9,
		reviewCount: 3200,
		sido: "경북",
		gugun: "울릉군",
		contentTypeId: 12,
	},
	{
		id: 36,
		name: "청계천",
		category: "도시명소",
		address: "서울특별시 종로구 청계천로 1",
		latitude: 37.5697,
		longitude: 126.9783,
		description: "도심 속 생태하천으로 산책과 휴식을 즐길 수 있는 공간입니다.",
		imageUrl: "https://picsum.photos/seed/cheonggyecheon/400/300",
		rating: 4.2,
		reviewCount: 7100,
		sido: "서울",
		gugun: "종로구",
		contentTypeId: 12,
	},
	{
		id: 37,
		name: "홍대 거리",
		category: "도시명소",
		address: "서울특별시 마포구 와우산로",
		latitude: 37.5565,
		longitude: 126.9237,
		description: "젊은이들의 문화와 예술이 살아있는 활기찬 거리입니다.",
		imageUrl: "https://picsum.photos/seed/hongdae/400/300",
		rating: 4.1,
		reviewCount: 11400,
		sido: "서울",
		gugun: "마포구",
		contentTypeId: 32,
	},
	{
		id: 38,
		name: "이태원",
		category: "도시명소",
		address: "서울특별시 용산구 이태원로",
		latitude: 37.5346,
		longitude: 126.994,
		description: "다양한 문화와 음식을 즐길 수 있는 국제적인 거리입니다.",
		imageUrl: "https://picsum.photos/seed/itaewon/400/300",
		rating: 4.0,
		reviewCount: 8900,
		sido: "서울",
		gugun: "용산구",
		contentTypeId: 32,
	},
	{
		id: 39,
		name: "부산 국제시장",
		category: "시장",
		address: "부산광역시 중구 신창동 4가 1-1",
		latitude: 35.1018,
		longitude: 129.0298,
		description: "6.25 전쟁 이후 피난민들이 형성한 역사적인 재래시장입니다.",
		imageUrl: "https://picsum.photos/seed/gukje/400/300",
		rating: 4.2,
		reviewCount: 7300,
		sido: "부산",
		gugun: "중구",
		contentTypeId: 38,
	},
	{
		id: 40,
		name: "춘천 닭갈비골목",
		category: "음식",
		address: "강원도 춘천시 명동길",
		latitude: 37.8812,
		longitude: 127.7278,
		description: "춘천 명물 닭갈비와 막국수를 즐길 수 있는 먹거리 골목입니다.",
		imageUrl: "https://picsum.photos/seed/dakkgalbi/400/300",
		rating: 4.3,
		reviewCount: 6500,
		sido: "강원",
		gugun: "춘천시",
		contentTypeId: 39,
	},
	{
		id: 41,
		name: "해인사 팔만대장경",
		category: "문화재",
		address: "경상남도 합천군 가야면 해인사길 122",
		latitude: 35.7988,
		longitude: 128.1009,
		description: "팔만대장경을 보관하는 유네스코 세계문화유산 사찰입니다.",
		imageUrl: "https://picsum.photos/seed/haeinsa/400/300",
		rating: 4.6,
		reviewCount: 7900,
		sido: "경남",
		gugun: "합천군",
		contentTypeId: 76,
	},
	{
		id: 42,
		name: "제주 우도",
		category: "자연",
		address: "제주특별자치도 제주시 우도면",
		latitude: 33.5039,
		longitude: 126.9523,
		description: "아름다운 에메랄드빛 바다가 펼쳐진 제주의 작은 섬입니다.",
		imageUrl: "https://picsum.photos/seed/udo/400/300",
		rating: 4.7,
		reviewCount: 13700,
		sido: "제주",
		gugun: "제주시",
		contentTypeId: 12,
	},
	{
		id: 43,
		name: "남해 독일마을",
		category: "문화",
		address: "경상남도 남해군 삼동면 독일로 92",
		latitude: 34.8302,
		longitude: 127.9315,
		description: "독일 파독 광부와 간호사들이 조성한 이국적인 마을입니다.",
		imageUrl: "https://picsum.photos/seed/germanvillage/400/300",
		rating: 4.3,
		reviewCount: 5100,
		sido: "경남",
		gugun: "남해군",
		contentTypeId: 14,
	},
	{
		id: 44,
		name: "경복궁 야간개장",
		category: "문화재",
		address: "서울특별시 종로구 사직로 161",
		latitude: 37.5796,
		longitude: 126.977,
		description:
			"야간에 특별 개장하여 조명으로 빛나는 궁궐의 신비로운 모습을 감상할 수 있습니다.",
		imageUrl: "https://picsum.photos/seed/gyeongbokgung-night/400/300",
		rating: 4.9,
		reviewCount: 6400,
		sido: "서울",
		gugun: "종로구",
		contentTypeId: 76,
	},
	{
		id: 45,
		name: "포항 호미곶",
		category: "자연",
		address: "경상북도 포항시 남구 호미곶면 해맞이로 136",
		latitude: 36.0771,
		longitude: 129.5701,
		description: "한반도 최동단에서 일출을 감상할 수 있는 명소입니다.",
		imageUrl: "https://picsum.photos/seed/homigot/400/300",
		rating: 4.5,
		reviewCount: 7200,
		sido: "경북",
		gugun: "포항시",
		contentTypeId: 12,
	},
	{
		id: 46,
		name: "청주 고인돌 공원",
		category: "문화재",
		address: "충청북도 청주시 흥덕구",
		latitude: 36.6424,
		longitude: 127.4293,
		description: "선사시대 고인돌을 볼 수 있는 역사 유적 공원입니다.",
		imageUrl: "https://picsum.photos/seed/dolmen/400/300",
		rating: 4.0,
		reviewCount: 2300,
		sido: "충북",
		gugun: "청주시",
		contentTypeId: 76,
	},
	{
		id: 47,
		name: "진도 신비의 바닷길",
		category: "자연",
		address: "전라남도 진도군 고군면 회동리",
		latitude: 34.4298,
		longitude: 126.2551,
		description: "물이 갈라지는 신비로운 자연현상으로 유명한 바닷길입니다.",
		imageUrl: "https://picsum.photos/seed/jindo/400/300",
		rating: 4.5,
		reviewCount: 5900,
		sido: "전남",
		gugun: "진도군",
		contentTypeId: 12,
	},
	{
		id: 48,
		name: "제천 청풍명월",
		category: "자연",
		address: "충청북도 제천시 금성면 청풍호로 1167",
		latitude: 36.9869,
		longitude: 128.1683,
		description: "청풍호를 배경으로 한 아름다운 자연경관이 펼쳐집니다.",
		imageUrl: "https://picsum.photos/seed/cheongpung/400/300",
		rating: 4.3,
		reviewCount: 4600,
		sido: "충북",
		gugun: "제천시",
		contentTypeId: 12,
	},
	{
		id: 49,
		name: "대전 엑스포과학공원",
		category: "관광지",
		address: "대전광역시 유성구 대덕대로 480",
		latitude: 36.3763,
		longitude: 127.3869,
		description: "1993년 대전 엑스포가 열렸던 과학 테마 공원입니다.",
		imageUrl: "https://picsum.photos/seed/daejeon-expo/400/300",
		rating: 4.1,
		reviewCount: 4100,
		sido: "대전",
		gugun: "유성구",
		contentTypeId: 12,
	},
	{
		id: 50,
		name: "광주 국립아시아문화전당",
		category: "문화",
		address: "광주광역시 동구 문화전당로 38",
		latitude: 35.1463,
		longitude: 126.9226,
		description: "아시아 문화 교류의 중심지로 다양한 전시와 공연이 열립니다.",
		imageUrl: "https://picsum.photos/seed/acc/400/300",
		rating: 4.3,
		reviewCount: 5800,
		sido: "광주",
		gugun: "동구",
		contentTypeId: 14,
	},
];

export const useAttractionsStore = defineStore("attractions", () => {
	const items = ref<Attraction[]>([...SEED_ATTRACTIONS]);
	const loading = ref(false);
	const error = ref<string | null>(null);
	const searchQuery = ref("");
	const selectedCategory = ref("");
	const selectedSido = ref("");

	const categories = computed(() => [
		...new Set(SEED_ATTRACTIONS.map((a) => a.category)),
	]);

	const sidos = computed(() => [
		...new Set(SEED_ATTRACTIONS.map((a) => a.sido)),
	]);

	const filtered = computed(() => {
		return items.value.filter((a) => {
			const matchesSearch =
				!searchQuery.value ||
				a.name.includes(searchQuery.value) ||
				a.address.includes(searchQuery.value) ||
				a.description.includes(searchQuery.value);
			const matchesCategory =
				!selectedCategory.value || a.category === selectedCategory.value;
			const matchesSido = !selectedSido.value || a.sido === selectedSido.value;
			return matchesSearch && matchesCategory && matchesSido;
		});
	});

	function getById(id: number): Attraction | undefined {
		return items.value.find((a) => a.id === id);
	}

	/** BE 연결 시 이 함수만 교체 */
	async function fetchAttractions(): Promise<void> {
		loading.value = true;
		error.value = null;
		// mockup: 이미 items에 하드코딩 데이터 있음
		await new Promise((r) => setTimeout(r, 100));
		loading.value = false;
	}

	function setSearch(query: string) {
		searchQuery.value = query;
	}

	function setCategory(category: string) {
		selectedCategory.value = category;
	}

	function setSido(sido: string) {
		selectedSido.value = sido;
	}

	return {
		items,
		loading,
		error,
		searchQuery,
		selectedCategory,
		selectedSido,
		categories,
		sidos,
		filtered,
		getById,
		fetchAttractions,
		setSearch,
		setCategory,
		setSido,
	};
});
